"""统一时间轴（子项目 2 设计 §4）：纯能力层，只依赖标准库和 pydantic。"""

from studio.timeline.build import (
    GridInput,
    LayerNotSupported,
    MomentInput,
    MusicInput,
    NarrationInput,
    SectionInput,
    TimedSectionInput,
    TimelineError,
    TimelineLayers,
    build_timeline,
    narration_from_documents,
    timeline_hash,
)
from studio.timeline.imported import (
    ImportLayers,
    downbeat_times,
    effective_grid,
    import_hash,
    layers_from_import,
)
from studio.timeline.notation import parse_at
from studio.timeline.schema import (
    Beat,
    Energy,
    Grid,
    Moment,
    Music,
    MusicEvent,
    NarrationScene,
    Section,
    Timeline,
)

__all__ = [
    "Beat",
    "Energy",
    "Grid",
    "GridInput",
    "ImportLayers",
    "LayerNotSupported",
    "Moment",
    "MomentInput",
    "Music",
    "MusicEvent",
    "MusicInput",
    "NarrationInput",
    "NarrationScene",
    "Section",
    "SectionInput",
    "TimedSectionInput",
    "Timeline",
    "TimelineError",
    "TimelineLayers",
    "build_timeline",
    "downbeat_times",
    "effective_grid",
    "import_hash",
    "layers_from_import",
    "narration_from_documents",
    "parse_at",
    "timeline_hash",
]
